name: Create Azure Container Registry

on: workflow_dispatch

permissions:
   id-token: write # Require write permission to Fetch an OIDC token.
   contents: read # Required to read repository contents
   actions: read # Required for GitHub Actions
   checks: write # Required for status checks

env:
   RESOURCE_GROUP: demoRG3
   AKS_CLUSTER_NAME: demoAKSCluster
   ACR_NAME: demoacr0003

jobs:
   create-acr:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Azure Login
       uses: azure/login@v2
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
 
     - name: Create Azure Container Registry
       uses: azure/cli@v2
       with:
         azcliversion: latest
         inlineScript: |
           az acr create --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.ACR_NAME }} --sku Basic

     - name: Docker build and push ACR
       run: |
         az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
         docker build ./src/ --tag ${{ secrets.ACR_LOGIN_SERVER }}/myapp:v1
         docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:v1

    # Set the target AKS cluster.
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
       resource-group: '${{ env.RESOURCE_GROUP }}' 
       cluster-name: '${{ env.AKS_CLUSTER_NAME }}'
   
    - name: Create Kubernetes Secret with ACR credentials
      uses: Azure/k8s-create-secret@v3
      with:
       container-registry-url: ${{ secrets.ACR_LOGIN_SERVER }}
       container-registry-username: ${{ secrets.ACR_USERNAME }}
       container-registry-password: ${{ secrets.ACR_PASSWORD }}
       secret-name: k8s-secret

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v3
      with:
       manifests: |
         k8s/myapp-deployment.yml
         k8s/myapp-deployment.yml
       images: |
         ${{ secrets.ACR_LOGIN_SERVER }}/myapp:v1
       imagepullsecrets: |
         k8s-secret
