name: Create Azure Container Registry

on:
push:
  branches:
    - main

permissions:
   id-token: write # Require write permission to Fetch an OIDC token.
   contents: read # Required to read repository contents
   actions: read # Required for GitHub Actions
   checks: write # Required for status checks

env:
   RESOURCE_GROUP: demoRG3
   AKS_CLUSTER_NAME: demoAKSCluster
   ACR_NAME: demoACR0003

jobs:
   create-acr:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Azure Login
       uses: azure/login@v2
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
 
     - name: Create Azure Container Registry
       uses: azure/cli@v2
       with:
         azcliversion: latest
         inlineScript: |
           az acr create --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.ACR_NAME }} --sku Basic
